CREATE DATABASE IF NOT EXISTS `vivasgram`;
USE `vivasgram`;


	CREATE TABLE IF NOT EXISTS `usuarios` (
  		ID INT(5) NOT NULL AUTO_INCREMENT,
  		NOMBREUSUARIO varchar(55) DEFAULT NULL,
  		PUERTO INT(9) DEFAULT NULL,
		PRIMARY KEY (ID)
	) ENGINE=InnoDB DEFAULT CHARSET=UTF8;

